[package]
name = "twentyrone"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
serde = "1.0.228"
serde_json = "1.0.149"
serenity = "0.12.5"
tokio = { version = "1", features = ["full"] }


